apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: default
data:
  POSTGRES_USER: "myapp"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "my_app_development"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  DATABASE_URL: postgres://myapp:password@db:5432/my_app_development
